# Generated by Django 2.0 on 2020-02-12 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countydata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('county', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='crownstoresdata',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('latitude', models.CharField(max_length=80)),
                ('longitude', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Driversdata',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=20)),
                ('m_name', models.CharField(max_length=20)),
                ('contacts', models.IntegerField()),
                ('truck', models.CharField(max_length=20)),
                ('truck_speed', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='roadsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnode_field', models.BigIntegerField()),
                ('tnode_field', models.BigIntegerField()),
                ('lpoly_field', models.BigIntegerField()),
                ('rpoly_field', models.BigIntegerField()),
                ('length', models.FloatField()),
                ('kenroad_field', models.BigIntegerField()),
                ('kenroad_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Roads',
            },
        ),
        migrations.CreateModel(
            name='townsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('ktowns_field', models.BigIntegerField()),
                ('ktowns_id', models.BigIntegerField()),
                ('town_name', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Towns',
            },
        ),
    ]
