# Generated by Django 2.0 on 2020-02-15 05:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('latitude', models.CharField(max_length=80)),
                ('longitude', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Distribution Centers',
            },
        ),
        migrations.RenameModel(
            old_name='countydata',
            new_name='Counties',
        ),
        migrations.RenameModel(
            old_name='roadsdata',
            new_name='Roads',
        ),
        migrations.RenameModel(
            old_name='townsdata',
            new_name='Towns',
        ),
        migrations.DeleteModel(
            name='crownstoresdata',
        ),
        migrations.DeleteModel(
            name='Driversdata',
        ),
        migrations.AlterModelOptions(
            name='towns',
            options={'verbose_name_plural': 'Kenya Towns'},
        ),
    ]
